CatalogManager/Controllers/CatalogController.cs
using System;
using System.Text;
using System.Web.Mvc;
using CatalogManager.Models;

namespace CatalogManager.Controllers
{
    public class CatalogController : Controller
    {
        public Catalog catalog;

        public CatalogController()
        {
            catalog = CatalogSingleton.Instance;
        }

        //
        // GET: /Catalog/
        public ActionResult Index()
        {
            return View(catalog);
        }


        //
        // GET: /Catalog/Create
        public ActionResult CreateCategory()
        {
            return View();
        }

        //
        // POST: /Catalog/Create
        [HttpPost]
        public ActionResult CreateCategory(FormCollection collection)
        {
            var newCategoryName = collection["Name"];

            try
            {

                AddMainCategory(newCategoryName);

                return RedirectToAction("Index");
            }catch (ArgumentException e){
                ModelState.AddModelError("", "Category Already Exists, Must Be Unique: " + newCategoryName);
                return View();
            }
            catch (Exception e)
            {
                return View();
            }
        }

        public ActionResult FullCatalog()
        {
            return View(catalog);
        }

        public void AddMainCategory(string newCategoryName)
        {
            if (catalog.MainCategories.Contains(newCategoryName))
            {
                throw new ArgumentException();
            }
            catalog.MainCategories.Add(newCategoryName);
            catalog.AllCategories.Add(newCategoryName, new Category
            {
                Name = newCategoryName
            });
        }

        



    }
}

CatalogManager/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using CatalogManager.Models;

namespace CatalogManager.Controllers
{
    public class ProductController : Controller
    {
        public Dictionary<string, Category> allCategories;
        public Dictionary<string, Product> allProducts;
        public Catalog catalog;

        public ProductController()
        {
            catalog = CatalogSingleton.Instance;
            allProducts = ProductsSingleton.Instance;
            allCategories = CategoriesSingleton.Instance;
        }

        //
        // GET: /Product/
        public ActionResult Index(string name)
        {
            var category = allProducts[name];
            ViewBag.PreviousUrl = System.Web.HttpContext.Current.Request.UrlReferrer;
            return View(category);
        }

        //
        // GET: /Product/Create
        public ActionResult Create(string parentCategoryName)
        {
            ViewBag.PreviousUrl = System.Web.HttpContext.Current.Request.UrlReferrer;
            ViewBag.ParentCategoryName = parentCategoryName;
            return View();
        }

        //
        // POST: /Product/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                AddProduct(collection);
                
                return Redirect(collection["PreviousUrl"]);
            }
            catch (ArgumentException e)
            {
                ModelState.AddModelError("", "Product Already Exists, Must Be Unique: " + collection["Name"]);
                ViewBag.PreviousUrl = collection["PreviousUrl"];
                ViewBag.ParentCategoryName = collection["ParentCategoryName"];
                return View();
            }
            catch (Exception e)
            {
                ViewBag.PreviousUrl = collection["PreviousUrl"];
                ViewBag.ParentCategoryName = collection["ParentCategoryName"];
                return View();
            }
        }

        //
        // GET: /Product/Edit/5
        public ActionResult Edit(string name, string parentCategoryName)
        {
            var product = allProducts[name];
            ViewBag.PreviousUrl = System.Web.HttpContext.Current.Request.UrlReferrer;
            ViewBag.ParentCategoryName = parentCategoryName;
            return View(product);
        }

        //
        // POST: /Category/Edit/5
        [HttpPost]
        public ActionResult Edit(string name, FormCollection collection)
        {
            try
            {
                EditProduct(name, collection);

                return Redirect(collection["PreviousUrl"]);
            }catch (ArgumentException e)
            {
                ModelState.AddModelError("", "Product Already Exists, Must Be Unique: " + name);
                ViewBag.PreviousUrl = collection["PreviousUrl"];
                ViewBag.ParentCategoryName = collection["ParentCategoryName"];
                return View();
            }
            catch (Exception e)
            {
                ViewBag.PreviousUrl = collection["PreviousUrl"];
                ViewBag.ParentCategoryName = collection["ParentCategoryName"];
                return View();
            }
        }

        //
        // GET: /Category/Delete/Name/PageType
        public ActionResult Delete(string name, string pageType)
        {
            if (pageType == "Main")
            {
                allProducts.Remove(name);
            }
            else if (pageType == "Category")
            {
                foreach (var entry in allCategories)
                {
                    if (entry.Value.Products.Contains(name))
                    {
                        entry.Value.Products.Remove(name);
                    }
                }
                allProducts.Remove(name);
            }

            return Redirect(System.Web.HttpContext.Current.Request.UrlReferrer.ToString());
        }

        public void AddProduct(FormCollection collection)
        {
            var newProductName = collection["Name"];

            if (allProducts.ContainsKey(newProductName))
            {
                throw new ArgumentException();
            }
            var parentCategoryName = collection["ParentCategoryName"];
            var parentCategory = allCategories[parentCategoryName];
            catalog.AllProducts.Add(newProductName, new Product
            {
                Name = newProductName,
                Price = Double.Parse(collection["Price"]),
                Description = collection["Description"]
            });
            parentCategory.Products.Add(newProductName);

        }

        public void EditProduct(string newProductName, FormCollection collection)
        {
            if (collection["originalProductName"] != newProductName && allProducts.ContainsKey(newProductName))
            {
                throw new ArgumentException();
            }
            var originalProduct = allProducts[collection["originalProductName"]];
            originalProduct.Name = newProductName;
            originalProduct.Description = collection["Description"];
            originalProduct.Price = Double.Parse(collection["Price"]);

            allProducts.Remove(collection["originalProductName"]);
            allProducts.Add(newProductName, originalProduct);

            foreach (var entry in allCategories)
            {
                if (entry.Value.Products.Contains(collection["originalProductName"]))
                {
                    entry.Value.Products.Remove(collection["originalProductName"]);
                    entry.Value.Products.Add(newProductName);
                }
            }
        }


    }
}

CatalogManager/Views/Shared/_CategoryPartial.cshtml
@model CatalogManager.Models.Category


<div class="row category">
    <h2>Category: @Html.ActionLink(@Model.Name, "Index", "Category", new { name = @Model.Name }, null)
    @Html.ActionLink("Update", "Edit", "Category", new {name = @Model.Name, @pageType = @ViewData["PageType"]}, new {@class = "btn btn-primary btn-large"})
    @Html.ActionLink("Delete", "Delete", "Category", new {name = @Model.Name, @pageType = @ViewData["PageType"]}, new {@class = "btn btn-primary btn-large"})
</div>

CatalogManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Steve's Catalog Manager</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">

            <div class="col-md-3">
                @Html.ActionLink("Steve's Catalog Manager", "Index", "Catalog", null, new {@class = "navbar-brand"})
            </div>
            <div class="col-md-4">
                @Html.ActionLink("Back To Catalog Top", "Index", "Catalog", null, new { @class = "navbar-brand" })
            </div>
            <div class="col-md-4">
                @Html.ActionLink("Output Full Catalog", "FullCatalog", "Catalog", null, new { @class = "navbar-brand" })
            </div>
            <div class="col-md-1 headerimage">
                <img src="http://images.enstarz.com/data/images/full/22437/best-buy.png" alt="Sample Image" width="50px" height="30px"/>
            </div>
      
    </div>
</div>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>

        <div class="col-md-11">
            <p>&copy; @DateTime.Now.Year - Steve's Catalog Manager</p>
        </div>
        <div class="col-md-1">
            <img src="http://images.enstarz.com/data/images/full/22437/best-buy.png" alt="Sample Image" width="50px" height="30px"/>
        </div>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", false)
</body>
</html>

CatalogManager/Views/Shared/_ProductPartial.cshtml
@model CatalogManager.Models.Product

<div class="col-md-3 product">
    <h2>Product: @Html.ActionLink(@Model.Name, "Index", "Product", new { name = @Model.Name }, null)</h2>

    
    @Html.ActionLink("Update", "Edit", "Product", new {name = @Model.Name, ViewBag.ParentCategoryName}, new {@class = "btn btn-primary btn-large"})
    @Html.ActionLink("Delete", "Delete", "Product", new {name = @Model.Name, @pageType = @ViewData["PageType"], ViewBag.ParentCategoryName}, new {@class = "btn btn-primary btn-large"})

</div>